"""
=============================================================================
Email Service
=============================================================================
Sends the generated PDF report to the user via SMTP with TLS.
Includes HTML email body, PDF attachment, and retry logic.
=============================================================================
"""

import os
import logging
import smtplib
import time
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication

from config.config import Config

logger = logging.getLogger(__name__)

# Maximum retry attempts for email delivery
MAX_RETRIES = 2
RETRY_DELAY = 3  # seconds


def send_report_email(to_email: str, name: str, company: str, pdf_path: str) -> bool:
    """
    Send the business report PDF via email.

    Args:
        to_email: Recipient email address.
        name:     Recipient's name (for personalization).
        company:  Company name (for the subject line).
        pdf_path: Absolute path to the generated PDF file.

    Returns:
        True if email was sent successfully, False otherwise.
    """
    # Validate SMTP configuration
    if not Config.SMTP_EMAIL or not Config.SMTP_PASSWORD:
        logger.error("SMTP credentials not configured — cannot send email")
        return False

    if not os.path.exists(pdf_path):
        logger.error(f"PDF file not found: {pdf_path}")
        return False

    # Build the email message
    msg = _build_email(to_email, name, company, pdf_path)

    # Attempt delivery with retries
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            logger.info(f"Sending email attempt {attempt}/{MAX_RETRIES} to {to_email}")
            _send_smtp(msg)
            logger.info(f"Email sent successfully to {to_email}")
            return True

        except smtplib.SMTPAuthenticationError as e:
            logger.error(f"SMTP authentication failed: {e}")
            return False  # No point retrying auth errors

        except smtplib.SMTPRecipientsRefused as e:
            logger.error(f"Recipient refused: {e}")
            return False  # No point retrying invalid recipients

        except Exception as e:
            logger.warning(f"Email attempt {attempt} failed: {e}")
            if attempt < MAX_RETRIES:
                time.sleep(RETRY_DELAY)
                continue
            logger.error(f"Email delivery failed after {MAX_RETRIES} attempts")
            return False


def _build_email(to_email: str, name: str, company: str, pdf_path: str) -> MIMEMultipart:
    """
    Build the MIME email message with HTML body and PDF attachment.
    """
    msg = MIMEMultipart()
    msg["Subject"] = f"Your Personalized Business Report — {company}"
    msg["From"] = Config.SMTP_EMAIL
    msg["To"] = to_email

    # HTML email body
    html_body = f"""
    <html>
    <body style="font-family: Arial, sans-serif; color: #333; line-height: 1.6;">
        <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
            <h2 style="color: #1a237e;">Your Business Audit Report is Ready!</h2>
            <p>Hi {name},</p>
            <p>Thank you for using <strong>LeadFlow AI</strong>. We've completed the
            business audit report for <strong>{company}</strong>.</p>
            <p>Please find the detailed PDF report attached to this email. The report includes:</p>
            <ul>
                <li>Company Overview</li>
                <li>Key Strengths Analysis</li>
                <li>Identified Weaknesses</li>
                <li>Growth Opportunities</li>
                <li>Strategic Recommendations</li>
            </ul>
            <p>If you have any questions about the report, feel free to reply to this email.</p>
            <hr style="border: 1px solid #e0e0e0; margin: 20px 0;">
            <p style="font-size: 12px; color: #999;">
                This report was automatically generated by LeadFlow AI.
                The analysis is for informational purposes only.
            </p>
        </div>
    </body>
    </html>
    """
    msg.attach(MIMEText(html_body, "html"))

    # Attach PDF
    pdf_filename = os.path.basename(pdf_path)
    with open(pdf_path, "rb") as f:
        pdf_attachment = MIMEApplication(f.read(), _subtype="pdf")
        pdf_attachment.add_header(
            "Content-Disposition", "attachment", filename=pdf_filename
        )
        msg.attach(pdf_attachment)

    return msg


def _send_smtp(msg: MIMEMultipart) -> None:
    """
    Send the email via SMTP with TLS.
    Raises exceptions on failure for retry handling.
    """
    with smtplib.SMTP(Config.SMTP_SERVER, Config.SMTP_PORT, timeout=30) as server:
        server.ehlo()
        server.starttls()
        server.ehlo()
        server.login(Config.SMTP_EMAIL, Config.SMTP_PASSWORD)
        server.send_message(msg)
